In [ ]:
import numpy as np

##**CREATE NumPy ARRAYS**

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]) # Created array
type(temperatures_w1)

numpy.ndarray

##**INSPECTION AND PROPERTIES**

In [ ]:
temperatures_w1.shape # Shape of the array

(7,)

In [ ]:
temperatures_w1.dtype # Data type of the array

dtype('float64')

In [ ]:
temperatures_w1.size #No.Of Elements in the array

7

In [ ]:
temperature = (temperatures_w1 * 9/5) + 32 # Convert Celcius into Fahrenheit
print(temperature)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


##**ARRAY OPERATIONS**

In [ ]:
print("Minimum Temperature in Celcius: ",np.min(temperatures_w1))
print("Minimum Temperature in Fahrenheit: ",np.min(temperature))
print("Maximum Temperature in Celcius: ",np.max(temperatures_w1))
print("Maximum Temperature in Fahrenheit: ",np.max(temperature))
print("Average Temperature in Celcius: ",np.mean(temperatures_w1))
print("Average Temperature in Fahrenheit: ",np.mean(temperature))


Minimum Temperature in Celcius:  20.8
Minimum Temperature in Fahrenheit:  69.44
Maximum Temperature in Celcius:  26.1
Maximum Temperature in Fahrenheit:  78.98
Average Temperature in Celcius:  23.542857142857144
Average Temperature in Fahrenheit:  74.37714285714286


##**ARRAY SLICING AND INDEXING**

In [ ]:
#Extract the temperatures for the first three days of the week.

print(f"Temperatures for the first three days in Celcius: {temperatures_w1[:3]}")
print(f"Temperatures for the first three days in Fahrenheit: {temperature[:3]}")

Temperatures for the first three days in Celcius: [22.5 25.3 20.8]
Temperatures for the first three days in Fahrenheit: [72.5  77.54 69.44]


In [ ]:
#Extract the temperatures for the weekend (last two days)
print(f"Temperatures for the weekend in Celcius: {temperatures_w1[-2:]}")
print(f"Temperatures for the weekend in Fahrenheit: {temperature[-2:]}")

Temperatures for the weekend in Celcius: [24.8 21.9]
Temperatures for the weekend in Fahrenheit: [76.64 71.42]


In [ ]:
#Extract the temperatures for the middle three days of the week
print(f"Temperatures for the weekend in Celcius: {temperatures_w1[2:5:]}")
print(f"Temperatures for the weekend in Fahrenheit: {temperature[2:5:]}")

Temperatures for the weekend in Celcius: [20.8 23.4 26.1]
Temperatures for the weekend in Fahrenheit: [69.44 74.12 78.98]


##**CREATE A 2D ARRAY**


In [ ]:
Row_1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
Row_2 = [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
temperatures = np.array([Row_1, Row_2])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


##**INSPECT AND SLICE THE 2D ARRAY**

In [ ]:
temperatures.shape # shape of the 2D Array

(2, 7)

In [ ]:
temperatures.dtype # Data type of the 2D Array

dtype('float64')

In [ ]:
temperatures.size # Size of the 2D Array

14

In [ ]:
# The temperatures for the first week (Row 1).
week1_temperatures = temperatures[0, :]
print(f"Temperatures for the first week: {week1_temperatures}")

Temperatures for the first week: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
#The temperatures for the second week (Row 2)
week2_temperatures = temperatures[1, :]
print(f"Temperatures for the second week: {week2_temperatures}")

Temperatures for the second week: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
#The temperatures for the first three days of each week
temperatures[:, :3]

array([[22.5, 25.3, 20.8],
       [19.2, 22.5, 21.3]])

In [ ]:
#The temperatures for the weekends (last two days) of both weeks
temperatures[:, -2:]

array([[24.8, 21.9],
       [22.8, 20.1]])